model_family: llama2-7b
model_path: /data/irfan/finetune/MUSE-News_knowmem_all

save_dir: ./MUSE-News

#dataset path for each of the 4 datasets to be evaluated
# data_path: [/home/irfan/machine unlearning/DrvKnowledge/a_new_data/forget25.csv,/home/irfan/machine unlearning/DrvKnowledge/a_new_data/derivative25.csv, /home/irfan/machine unlearning/DrvKnowledge/data/TOFU_normal_perturbed.csv, /home/irfan/machine unlearning/DrvKnowledge/a_new_data/retain75derivative25.csv, /home/irfan/machine unlearning/DrvKnowledge/a_new_data/retain75_perturbed.csv]
data_path: [/home/irfan/machine unlearning/DrvKnowledge/MUSE_data/MUSE-News_knowmem_forget_qa.csv, /home/irfan/machine unlearning/DrvKnowledge/MUSE_data/MUSE-News_knowmem_derivative_qa.csv, /home/irfan/machine unlearning/DrvKnowledge/MUSE_data/MUSE-News_knowmem_retain_qa.csv]

split: forget25
split_list:
  - retain_perturbed
  - retain_base
  - world_facts_perturbed


question_key: [question, question, question]
answer_key: [answer, answer, answer]

base_answer_key: [answer, answer, answer]
perturbed_answer_key: [answer, answer, answer]

# eval_task: [forget_log, derivative_log, normal_log, retain_log, forget_truth_log]
eval_task: [forget_log, derivative_log, retain_log]

generation:
  max_length: 200
  max_new_tokens: null

save_generated_text: true

ds_size: 200

overwrite: true
use_pretrained: false

batch_size: 32
reinitialize_weights: false

retain_result: null