model_family: llama2-7b

LoRA:
  r: 8
  alpha: 32
  dropout: 0.05

data_path: locuslab/TOFU
split: full
batch_size: 32
gradient_accumulation_steps: 4
num_epochs: 1
lr: 1e-5
save_dir: /data/irfan/TOFU/ft_epoch${num_epochs}_lr${lr}_${model_family}_${split}_wd${weight_decay}

weight_decay: 0.01
seed: 42