model_family: llama2-7b
model_path: /data/irfan/finetune/MUSE-News_knowmem_all
LoRA:
  r: 8
  alpha: 32
  dropout: 0.05

lr: 1e-4
split: forget5
forget_data_path: ../DrvKnowledge/MUSE_data/MUSE-News_knowmem_forget_qa.csv
derivative_data_path: ../DrvKnowledge/MUSE_data/MUSE-News_knowmem_derivative_qa.csv
retain_data_path: ../DrvKnowledge/MUSE_data/MUSE-News_knowmem_retain_qa.csv
batch_size: 4
gradient_accumulation_steps: 1
num_epochs: 5

forget_loss: GA
retain_loss: GD
derivative_loss: GD
use_drv: true
use_rt: false

# specify in utils.py
save_dir: /data/irfan/unlearn_new/${forget_loss}_${lr}_${split}_${num_epochs}_forget25

overwrite_dir: false
weight_decay: 0
save_model: true
eval_while_train: false
eval_only: false
seed: 42

eval:
  # retain_result: data/retain90_llama_wd0.01/eval_results/ds_size300/eval_log_aggregated.json
  model_path: locuslab/tofu_ft_llama2-7b
  model_family: ${..model_family}
  save_dir: ${..save_dir}
  data_path: [locuslab/TOFU, locuslab/TOFU, locuslab/TOFU, locuslab/TOFU]
  split: ${..split}_perturbed
  split_list:
    - retain_perturbed
    - real_authors_perturbed
    - world_facts_perturbed
    - ${split}

  eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]
  question_key: [question, question, question, question]
  answer_key: [answer, answer, answer, answer]
  base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
  perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

  generation:
    max_length: 200
    max_new_tokens: null

  save_generated_text: true

  ds_size: 300

  overwrite: true
  use_pretrained: false

  batch_size: 30
  retain_result: null